id = "rl"
name = "RL"
version = "0.1.0"
schema_version = 1
description = "rl language support"
authors = ["MohamedGonem"]
repository = "https://github.com/MohamedGonem/tree-sitter-rl"

[grammars.rl]
repository = "https://github.com/MohamedGonem/tree-sitter-rl"
commit = "0de622a0625c5e22c28cd63e65003063ee8b97ce"

[language_servers.rl-lsp]
languages = ["rl"]
